-- MySQL Script generated by MySQL Workbench
-- Mon May 15 23:51:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portfolio` DEFAULT CHARACTER SET utf8mb3 ;
USE `portfolio` ;

-- -----------------------------------------------------
-- Table `portfolio`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`persona` (
  `id_persona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `url_foto` VARCHAR(100) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_persona`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `portfolio`.`tipo_conocimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`tipo_conocimiento` (
  `id_tipo_conocimiento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_conocimiento`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `portfolio`.`conocimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`conocimiento` (
  `id_conocimiento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `porcentaje` INT NOT NULL,
  `persona_id_persona` INT NOT NULL,
  `tipo_conocimiento_id_tipo_conocimiento` INT NOT NULL,
  PRIMARY KEY (`id_conocimiento`, `persona_id_persona`, `tipo_conocimiento_id_tipo_conocimiento`),
  INDEX `fk_conocimiento_persona1_idx` (`persona_id_persona` ASC) VISIBLE,
  INDEX `fk_conocimiento_tipo_conocimiento1_idx` (`tipo_conocimiento_id_tipo_conocimiento` ASC) VISIBLE,
  CONSTRAINT `fk_conocimiento_persona1`
    FOREIGN KEY (`persona_id_persona`)
    REFERENCES `portfolio`.`persona` (`id_persona`),
  CONSTRAINT `fk_conocimiento_tipo_conocimiento1`
    FOREIGN KEY (`tipo_conocimiento_id_tipo_conocimiento`)
    REFERENCES `portfolio`.`tipo_conocimiento` (`id_tipo_conocimiento`))
ENGINE = InnoDB
AUTO_INCREMENT = 151
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `portfolio`.`educacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`educacion` (
  `id_educacion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `institucion` VARCHAR(45) NOT NULL,
  `fecha_desde` DATE NOT NULL,
  `fecha_hasta` DATE NULL DEFAULT NULL,
  `actualmente` TINYINT(1) NOT NULL,
  `persona_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_educacion`, `persona_id_persona`),
  INDEX `fk_educacion_persona_idx` (`persona_id_persona` ASC) VISIBLE,
  CONSTRAINT `fk_educacion_persona`
    FOREIGN KEY (`persona_id_persona`)
    REFERENCES `portfolio`.`persona` (`id_persona`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `portfolio`.`tipo_trabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`tipo_trabajo` (
  `id_tipo_trabajo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo_trabajo`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `portfolio`.`experiencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`experiencia` (
  `id_experiencia` INT NOT NULL AUTO_INCREMENT,
  `url_foto` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `fecha_desde` DATE NOT NULL,
  `fecha_hasta` DATE NULL DEFAULT NULL,
  `actualmente` TINYINT(1) NOT NULL,
  `persona_id_persona` INT NOT NULL,
  `tipo_trabajo_id_tipo_trabajo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_experiencia`, `persona_id_persona`, `tipo_trabajo_id_tipo_trabajo`),
  INDEX `fk_experiencia_persona1_idx` (`persona_id_persona` ASC) VISIBLE,
  INDEX `fk_experiencia_tipo_trabajo1_idx` (`tipo_trabajo_id_tipo_trabajo` ASC) VISIBLE,
  CONSTRAINT `fk_experiencia_persona1`
    FOREIGN KEY (`persona_id_persona`)
    REFERENCES `portfolio`.`persona` (`id_persona`),
  CONSTRAINT `fk_experiencia_tipo_trabajo1`
    FOREIGN KEY (`tipo_trabajo_id_tipo_trabajo`)
    REFERENCES `portfolio`.`tipo_trabajo` (`id_tipo_trabajo`))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `portfolio`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`proyecto` (
  `id_proyecto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `url_proyecto` VARCHAR(100) NOT NULL,
  `fecha_desde` DATE NOT NULL,
  `fecha_hasta` DATE NULL DEFAULT NULL,
  `actualmente` TINYINT(1) NOT NULL,
  `url_foto` VARCHAR(100) NOT NULL,
  `persona_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_proyecto`, `persona_id_persona`),
  INDEX `fk_proyecto_persona1_idx` (`persona_id_persona` ASC) VISIBLE,
  CONSTRAINT `fk_proyecto_persona1`
    FOREIGN KEY (`persona_id_persona`)
    REFERENCES `portfolio`.`persona` (`id_persona`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `portfolio`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`tipo_usuario` (
  `id_tipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `portfolio`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `tipo_usuario_id_tipo_usuario` INT NOT NULL,
  `persona_id_persona` INT NOT NULL,
  `rol` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_usuario`, `tipo_usuario_id_tipo_usuario`, `persona_id_persona`),
  INDEX `fk_usuario_tipo_usuario1_idx` (`tipo_usuario_id_tipo_usuario` ASC) VISIBLE,
  INDEX `fk_usuario_persona1_idx` (`persona_id_persona` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_persona1`
    FOREIGN KEY (`persona_id_persona`)
    REFERENCES `portfolio`.`persona` (`id_persona`),
  CONSTRAINT `fk_usuario_tipo_usuario1`
    FOREIGN KEY (`tipo_usuario_id_tipo_usuario`)
    REFERENCES `portfolio`.`tipo_usuario` (`id_tipo_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
